version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

networks:
  default:
    external:
      name: frontend