"""add tables

Revision ID: 775b272a1d9b
Revises: 
Create Date: 2022-04-29 10:24:14.157035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '775b272a1d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('table_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('prepare_time', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='fk_item_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], name='fk_table_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_item_id', 'order', ['item_id'], unique=False)
    op.create_index('ix_table_id', 'order', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_table_id', 'order', type_='foreignkey')
    op.drop_constraint('fk_item_id', 'order', type_='foreignkey')
    op.drop_index('ix_table_id', table_name='order')
    op.drop_index('ix_item_id', table_name='order')
    op.drop_table('order')
    op.drop_table('table')
    op.drop_table('item')
    # ### end Alembic commands ###
