"""create tables

Revision ID: 9c8dfcd4d0e4
Revises: 
Create Date: 2022-04-23 20:31:33.539269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c8dfcd4d0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('duration', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('table_id', mysql.INTEGER(display_width=10, unsigned=True), sa.ForeignKey("table.id"), nullable=False),
    sa.Column('item_id', mysql.INTEGER(display_width=10, unsigned=True), sa.ForeignKey("item.id"), nullable=False),
    sa.Column('ended_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('table_id_item_id', 'order', ['table_id', 'item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_ibfk_1', 'order', type_='foreignkey')
    op.drop_constraint('order_ibfk_2', 'order', type_='foreignkey')
    op.drop_index('table_id_item_id', table_name='order')
    op.drop_table('order')
    op.drop_table('table')
    op.drop_table('item')
    # ### end Alembic commands ###
