version: '3.8'

services:
  restaurant-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: restaurant-api
    container_name: restaurant-api
    restart: always
    networks:
      - restaurant-network
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports: 
      - "8000:80"
    command: uvicorn asgi:app --host 0.0.0.0 --port 80

networks:
  restaurant-network:
    name: restaurant-network