version: '3.8'

services:
  restaurant-mysql:
    image: mysql:8.0
    container_name: restaurant-mysql
    platform: linux/amd64
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: restaurant
      MYSQL_USER: restaurant
      MYSQL_PASSWORD: restaurant
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u restaurant --password=restaurant
  restaurant-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: restaurant-api
    container_name: restaurant-api
    restart: always
    networks:
      - backend
      - frontend
    volumes:
      - .:/usr/src/app
    env_file: .env
    ports: 
      - "8000:80"
    command: bash -c "alembic upgrade head && uvicorn --http httptools asgi:app --host 0.0.0.0 --port 80"
    depends_on:
      restaurant-mysql:
        condition: service_healthy
networks:
  backend:
    name: backend
  frontend:
    name: frontend