FROM python:3.10-slim
ARG PIPENV_DEV=0
ENV PIPENV_DEV=$PIPENV_DEV

WORKDIR /usr/src/app/

RUN apt-get update && \
    apt-get upgrade -y && \
    pip install pipenv

COPY ./Pipfile ./Pipfile.lock ./

RUN pipenv lock -r > requirements.txt && \ 
    pip install -r requirements.txt

COPY . .